 export const projectSets = [
    {
      images: [
        { id: 1, src: "/assets/p1.jpg", alt: "Project 1 Image 1", title: 'Delight in Every Portrait - Vivo Pakistan1', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum. ' },
        { id: 2, src: "/assets/p2.jpg", alt: "Project 1 Image 2", title: 'Delight in Every Portrait - Vivo Pakistan2', description: 'do eiusmod tempor incididunt ut labore et dolore magna do eiusmod tempor incididunt ut labore et dolore magna do eiusmod tempor incididunt ut labore et dolore magna do eiusmod tempor incididunt ut labore et dolore magna do eiusmod tempor incididunt ut labore et dolore magna do eiusmod tempor incididunt ut labore et dolore magna do eiusmod tempor incididunt ut labore et dolore magna do eiusmod tempor incididunt ut labore et dolore magna do eiusmod tempor incididunt ut labore et dolore magna do eiusmod tempor incididunt ut labore et dolore magna do eiusmod tempor incididunt ut labore et dolore magna do eiusmod tempor incididunt ut labore et dolore magna do eiusmod tempor incididunt ut labore et dolore magna do eiusmod tempor incididunt ut labore et dolore magnaanim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum. ' },
      ]
    },
    {
      images: [
        { id: 3, src: "/assets/p3.jpg", alt: "Project 2 Image 1", title: 'Delight in Every Portrait - Vivo Pakistan3', description: 'aliqua. Ut enim ad minim veniam, quis nostrud exercitation aliqua. Ut enim ad minim veniam, quis nostrud exercitation aliqua. Ut enim ad minim veniam, quis nostrud exercitation aliqua. Ut enim ad minim veniam, quis nostrud exercitation aliqua. Ut enim ad minim veniam, quis nostrud exercitation aliqua. Ut enim ad minim veniam, quis nostrud exercitation aliqua. Ut enim ad minim veniam, quis nostrud exercitation aliqua. Ut enim ad minim veniam, quis nostrud exercitation aliqua. Ut enim ad minim veniam, quis nostrud exercitation aliqua. Ut enim ad minim veniam, quis nostrud exercitation aliqua. Ut enim ad minim veniam, quis nostrud exercitation aliqua. Ut enim ad minim veniam, quis nostrud exercitation aliqua. Ut enim ad minim veniam, quis nostrud exercitation aliqua. Ut enim ad minim veniam, quis nostrud exercitation anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.' },
        { id: 4, src: "/assets/p4.jpg", alt: "Project 2 Image 2", title: 'Delight in Every Portrait - Vivo Pakistan4', description: 'ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.' },
      ]
    },
    {
      images: [
        { id: 5, src: "/assets/p5.jpg", alt: "Project 3 Image 1", title: 'Delight in Every Portrait - Vivo Pakistan5', description: 'aute irure dolor in reprehenderit in voluptate velit esse cillum aute irure dolor in reprehenderit in voluptate velit esse cillum aute irure dolor in reprehenderit in voluptate velit esse cillum aute irure dolor in reprehenderit in voluptate velit esse cillum aute irure dolor in reprehenderit in voluptate velit esse cillum aute irure dolor in reprehenderit in voluptate velit esse cillum aute irure dolor in reprehenderit in voluptate velit esse cillum aute irure dolor in reprehenderit in voluptate velit esse cillum aute irure dolor in reprehenderit in voluptate velit esse cillum aute irure dolor in reprehenderit in voluptate velit esse cillum aute irure dolor in reprehenderit in voluptate velit esse cillum aute irure dolor in reprehenderit in voluptate velit esse cillum aute irure dolor in reprehenderit in voluptate velit esse cillum aute irure dolor in reprehenderit in voluptate velit esse cillum anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.' },
        { id: 6, src: "/assets/p6.jpg", alt: "Project 3 Image 2", title: 'Delight in Every Portrait - Vivo Pakistan6', description: 'dolore eu fugiat nulla pariatur. Excepteur sint occaecat dolore eu fugiat nulla pariatur. Excepteur sint occaecat dolore eu fugiat nulla pariatur. Excepteur sint occaecat dolore eu fugiat nulla pariatur. Excepteur sint occaecat dolore eu fugiat nulla pariatur. Excepteur sint occaecat dolore eu fugiat nulla pariatur. Excepteur sint occaecat dolore eu fugiat nulla pariatur. Excepteur sint occaecat dolore eu fugiat nulla pariatur. Excepteur sint occaecat dolore eu fugiat nulla pariatur. Excepteur sint occaecat dolore eu fugiat nulla pariatur. Excepteur sint occaecat dolore eu fugiat nulla pariatur. Excepteur sint occaecat dolore eu fugiat nulla pariatur. Excepteur sint occaecat dolore eu fugiat nulla pariatur. Excepteur sint occaecat dolore eu fugiat nulla pariatur. Excepteur sint occaecatanim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum. ' },
      ]
    },
    {
      images: [
        { id: 7, src: "/assets/p7.jpg", alt: "Project 4 Image 1", title: 'Delight in Every Portrait - Vivo Pakistan7', description: 'cupidatat non proident, sunt in culpa qui officia deserunt mollit cupidatat non proident, sunt in culpa qui officia deserunt mollit cupidatat non proident, sunt in culpa qui officia deserunt mollit cupidatat non proident, sunt in culpa qui officia deserunt mollit cupidatat non proident, sunt in culpa qui officia deserunt mollit cupidatat non proident, sunt in culpa qui officia deserunt mollit cupidatat non proident, sunt in culpa qui officia deserunt mollit cupidatat non proident, sunt in culpa qui officia deserunt mollit cupidatat non proident, sunt in culpa qui officia deserunt mollit cupidatat non proident, sunt in culpa qui officia deserunt mollit cupidatat non proident, sunt in culpa qui officia deserunt mollit cupidatat non proident, sunt in culpa qui officia deserunt mollit cupidatat non proident, sunt in culpa qui officia deserunt mollit cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.' },
        { id: 8, src: "/assets/p8.jpg", alt: "Project 4 Image 2", title: 'Delight in Every Portrait - Vivo Pakistan8', description: 'anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.' },
      ]
    },
    {
      images: [
        { id: 9, src: "/assets/p9.jpg", alt: "Project 5 Image 1", title: 'Delight in Every Portrait - Vivo Pakistan9', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum. anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.' },
        { id: 10, src: "/assets/p10.jpg", alt: "Project 5 Image 2", title: 'Delight in Every Portrait - Vivo Pakistan10', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.anim id est laborum.' },
      ]
    },
  ];